DEFAULT_IGNORED_DIRS = {
    ".git",
    ".hg",
    ".svn",
    ".idea",
    ".vscode",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    ".next",
    ".nuxt",
    ".svelte-kit",
    "node_modules",
    "dist",
    "build",
    "coverage",
    ".venv",
    "venv",
    "env",
    ".tox",
    ".cache",
    "target",
    "out",
}

DEFAULT_IGNORED_FILES = {
    ".DS_Store",
    "Thumbs.db",
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "bun.lockb",
}

DEFAULT_IGNORED_EXTENSIONS = {
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".webp",
    ".bmp",
    ".ico",
    ".mp4",
    ".mp3",
    ".wav",
    ".ogg",
    ".mov",
    ".avi",
    ".zip",
    ".rar",
    ".7z",
    ".pdf",
    ".exe",
    ".dll",
    ".so",
    ".dylib",
    ".woff",
    ".woff2",
    ".ttf",
    ".eot",
    ".jar",
    ".class",
    ".pyc",
    ".pyd",
    ".o",
    ".a",
    ".obj",
    ".bin",
}

TEXT_EXTENSIONS = {
    ".py",
    ".pyi",
    ".js",
    ".jsx",
    ".ts",
    ".tsx",
    ".cjs",
    ".mjs",
    ".json",
    ".html",
    ".css",
    ".scss",
    ".sass",
    ".less",
    ".md",
    ".txt",
    ".toml",
    ".yml",
    ".yaml",
    ".ini",
    ".cfg",
    ".conf",
    ".env",
    ".sample",
    ".example",
    ".gitignore",
    ".editorconfig",
    ".sh",
    ".bat",
    ".cmd",
    ".ps1",
    ".sql",
    ".xml",
    ".svg",
}

MAX_BINARY_SNIFF_BYTES = 4096
MAX_SUMMARIZER_READ_CHARS = 16000
MAX_CODE_SNIPPET_CHARS = 12000